#!/bin/bash
# Generate include/build_number.h: a build identity derived from git.
#
# The number is the commit count and the codename is derived from the commit
# hash, so the identity is a function of the CODE, not of how many times
# someone has pressed make. Two people building the same commit get the same
# "0247 RoseLemon"; anyone building anything else gets something different.
# That is what makes a build number worth quoting in a bug report.
#
# Uncommitted changes append "+" - a dirty tree is by definition not the same
# build as the commit it sits on, and silently pretending otherwise is how you
# end up chasing a bug that only exists on one machine.
#
# Outside a git checkout it falls back to a local counter in build_number.txt,
# which is personal and not committed.
set -eu
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

COLOURS=(Red Green Blue Gold Silver Amber Coral Ivory Jade Mint
         Onyx Pearl Plum Rose Rust Sage Teal Umber Violet Cobalt)
FRUITS=(Apple Banana Cherry Damson Fig Grape Kiwi Lemon Mango Nectarine
        Olive Papaya Quince Raspberry Satsuma Tangerine Ugli Vanilla Walnut Yuzu)

if git rev-parse --git-dir >/dev/null 2>&1 && git rev-parse HEAD >/dev/null 2>&1; then
    N=$(git rev-list --count HEAD)
    SHA=$(git rev-parse --short=8 HEAD)
    # Two independent bytes of the hash pick the pair, so the codename is
    # stable for a commit and effectively random between commits.
    C=$(( 16#${SHA:0:2} % ${#COLOURS[@]} ))
    F=$(( 16#${SHA:2:2} % ${#FRUITS[@]} ))
    NAME="${COLOURS[$C]}${FRUITS[$F]}"
    if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
        SHA="$SHA+"
        NAME="$NAME+"
    fi
else
    [ -f build_number.txt ] || echo 0 > build_number.txt
    N=$(( $(cat build_number.txt) + 1 ))
    echo "$N" > build_number.txt
    NAME="${COLOURS[RANDOM % ${#COLOURS[@]}]}${FRUITS[RANDOM % ${#FRUITS[@]}]}"
    SHA="nogit"
fi

NUM=$(printf '%04d' "$N")

cat > include/build_number.h << HDR
/* Generated by tools/bump_build.sh - do not edit, do not commit. */
#pragma once
#define BUILD_NUMBER $N
#define BUILD_ID     "$NUM"
#define BUILD_NAME   "$NAME"
#define BUILD_SHA    "$SHA"
#define BUILD_DATE   "$(date '+%Y-%m-%d')"
HDR

echo "$NUM" > build_id.txt
printf '%s' "${NAME%+}" > build_name.txt   # '+' is not filename-friendly

echo "build $NUM $NAME ($SHA)"
